/**
 * Regenerates api-documentation.md at the repo root from the live route table:
 * every method, path, required role and request field comes from the code, so
 * the reference cannot drift. Run with `npm run docs:api`.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import type { RouteOptions } from 'fastify'
import type { ZodTypeAny } from 'zod'
import { zodToJsonSchema } from 'zod-to-json-schema'
import { buildApp } from '../app.js'
import { closeDb } from '../db/client.js'
import { closeRedis } from '../redis/client.js'
import { requireAuth } from '../modules/auth/rbac.js'

type Json = { type?: string | string[]; enum?: unknown[]; format?: string; items?: Json; properties?: Record<string, Json>; required?: string[]; anyOf?: Json[]; default?: unknown; minimum?: number; maximum?: number; maxLength?: number; const?: unknown }
type Route = { method: string; url: string; auth: string; params: string[]; query: string[]; body: string[]; response: string[] }

const OUT = fileURLToPath(new URL('../../../../api-documentation.md', import.meta.url))
const START = '<!-- generated:start -->'
const END = '<!-- generated:end -->'

const routes: Route[] = []

function typeOf(s: Json): string {
  if (s.const !== undefined) return JSON.stringify(s.const)
  if (s.enum) return s.enum.map((v) => JSON.stringify(v)).join(' \\| ')
  if (s.anyOf) return s.anyOf.map(typeOf).join(' \\| ')
  if (s.type === 'array') return `${s.items ? typeOf(s.items) : 'any'}[]`
  const t = Array.isArray(s.type) ? s.type.join(' \\| ') : (s.type ?? 'any')
  return s.format ? `${t} (${s.format})` : t
}

function fields(schema: unknown): string[] {
  if (!schema) return []
  const json = zodToJsonSchema(schema as ZodTypeAny, { $refStrategy: 'none' }) as Json
  const obj = json.anyOf?.find((s) => s.properties) ?? json
  if (!obj.properties) return [`(${typeOf(obj)})`]
  return Object.entries(obj.properties).map(([name, s]) => {
    const extra = [
      s.default !== undefined ? `default ${JSON.stringify(s.default)}` : '',
      s.minimum !== undefined || s.maximum !== undefined ? `${s.minimum ?? ''}–${s.maximum ?? ''}` : '',
      s.maxLength !== undefined ? `max ${s.maxLength} chars` : '',
    ].filter(Boolean)
    const req = obj.required?.includes(name) ? '' : '?'
    return `\`${name}${req}\` ${typeOf(s)}${extra.length ? ` (${extra.join(', ')})` : ''}`
  })
}

function auth(r: RouteOptions): string {
  const hooks = [r.onRequest, r.preHandler].flat().filter(Boolean) as Array<{ roles?: string[] }>
  const roles = hooks.flatMap((h) => h.roles ?? [])
  if (roles.length) return roles.join(', ')
  if (hooks.includes(requireAuth as never)) return 'any signed-in user'
  return 'public'
}

const app = await buildApp({
  onRoute: (r) => {
    const methods = [r.method].flat().filter((m) => m !== 'HEAD' && m !== 'OPTIONS')
    if (!r.url.startsWith('/v1') || methods.length === 0) return
    const s = (r.schema ?? {}) as Record<string, unknown>
    const ok = (s.response as Record<string, unknown> | undefined)?.[200] ?? (s.response as Record<string, unknown> | undefined)?.[201]
    for (const method of methods) {
      routes.push({
        method,
        url: r.url,
        auth: auth(r),
        params: fields(s.params),
        query: fields(s.querystring),
        body: fields(s.body),
        response: fields(ok).slice(0, 12),
      })
    }
  },
})
await app.ready()

const group = (url: string) => {
  const seg = url.split('/')[2] ?? ''
  return seg === 'admin' ? `admin/${url.split('/')[3]?.replace(/:.*/, '') ?? ''}` : seg
}
const byGroup = new Map<string, Route[]>()
for (const r of routes.sort((a, b) => a.url.localeCompare(b.url) || a.method.localeCompare(b.method))) {
  byGroup.set(group(r.url), [...(byGroup.get(group(r.url)) ?? []), r])
}

const list = (label: string, items: string[]) => (items.length ? `- **${label}:** ${items.join(' · ')}\n` : '')
let md = `${START}\n\n## Endpoint reference\n\n_Generated by \`npm run docs:api\` from the route table: ${routes.length} endpoints. Do not edit by hand._\n\n`
md += '| Group | Endpoints |\n|---|---|\n'
for (const [g, rs] of byGroup) md += `| [\`${g}\`](#${g.replace(/\//g, '')}) | ${rs.length} |\n`
for (const [g, rs] of byGroup) {
  md += `\n### ${g}\n`
  for (const r of rs) {
    md += `\n#### \`${r.method} ${r.url}\`\n\n- **Auth:** ${r.auth}\n`
    md += list('Path', r.params) + list('Query', r.query) + list('Body', r.body) + list('Returns', r.response)
  }
}
md += `\n${END}\n`

const current = readFileSync(OUT, 'utf8')
const [head] = current.split(START)
writeFileSync(OUT, `${head!.trimEnd()}\n\n${md}`)
console.log(`api-documentation.md: ${routes.length} endpoints in ${byGroup.size} groups`)

await app.close()
await closeDb()
await closeRedis()
