ALTER TABLE trips
ADD COLUMN IF NOT EXISTS stops JSONB,
ADD COLUMN IF NOT EXISTS return_stops JSONB,
ADD COLUMN IF NOT EXISTS return_drop_lat DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS return_drop_lng DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS return_drop_address TEXT,
ADD COLUMN IF NOT EXISTS vehicle_specs JSONB,
ADD COLUMN IF NOT EXISTS vision_mode TEXT,
ADD COLUMN IF NOT EXISTS flight_number TEXT,
ADD COLUMN IF NOT EXISTS requirement TEXT,
ADD COLUMN IF NOT EXISTS trip_type TEXT;
